# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 411b79f75b8fd2ab9a705f7638b65d1b9a9c72da81364e4a1f9f47763233b6296edb11b144db4d25236f04f8fe6eb34990f173c515357e702dbec0d5d039289a

test:
  secret_key_base: b181f1aaccda3c610917809f049e04f087a13c32f3ba27edfe129c7b630c8a797e8a360928c09ff423bfda1ca231e63f7f7a82f88d78bb20060c6dc3427c1e10

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
